"""Add currency field to payment

Revision ID: 244d0fc9deb7
Revises: 73c4b04a9b80
Create Date: 2025-04-15 13:48:34.634829

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "244d0fc9deb7"
down_revision: Union[str, None] = "73c4b04a9b80"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("currency", sa.String(length=3), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "currency")
    # ### end Alembic commands ###
