"""Add unique constraint to user and book in review model

Revision ID: 5a15735130bb
Revises: daf2ff5650e0
Create Date: 2025-04-11 19:51:44.192248

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a15735130bb"
down_revision: Union[str, None] = "daf2ff5650e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_book_user", "reviews", ["user_id", "book_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_book_user", "reviews", type_="unique")
    # ### end Alembic commands ###
