"""Remove total_amount field for order model

Revision ID: 73c4b04a9b80
Revises: 5a15735130bb
Create Date: 2025-04-14 12:51:37.605264

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "73c4b04a9b80"
down_revision: Union[str, None] = "5a15735130bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "total_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("total_amount", sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
