"""Add constraint for is_main field to BookImage model

Revision ID: 91f295d53227
Revises: ba3da027048e
Create Date: 2025-04-21 11:37:34.197316

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "91f295d53227"
down_revision: Union[str, None] = "ba3da027048e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "uq_book_main_image", "book_images", ["book_id"], unique=True, postgresql_where=sa.text("is_main = true")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_book_main_image", table_name="book_images", postgresql_where=sa.text("is_main = true"))
    # ### end Alembic commands ###
