"""Remove payment_method field of payment

Revision ID: b7d6261518f3
Revises: f6fc1e666d3c
Create Date: 2025-04-15 13:57:07.727088

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b7d6261518f3"
down_revision: Union[str, None] = "f6fc1e666d3c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "payment_method")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("payments", sa.Column("payment_method", sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
