"""Add constraint for is_primary field to Address model

Revision ID: ba3da027048e
Revises: eecf3f806860
Create Date: 2025-04-16 14:37:22.825436

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba3da027048e"
down_revision: Union[str, None] = "eecf3f806860"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("uq_user_primary_address", "addresses", ["user_id"], unique=True, postgresql_where=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_user_primary_address", table_name="addresses", postgresql_where=False)
    # ### end Alembic commands ###
