"""Update Book Category association field

Revision ID: daf2ff5650e0
Revises: 61c76e1d6937
Create Date: 2025-04-11 16:13:10.612054

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daf2ff5650e0"
down_revision: Union[str, None] = "61c76e1d6937"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uix_book_category", "book_categories", ["category_id", "book_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_book_category", "book_categories", type_="unique")
    # ### end Alembic commands ###
