"""Add status field to payments

Revision ID: eecf3f806860
Revises: b7d6261518f3
Create Date: 2025-04-15 15:23:27.607945

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "eecf3f806860"
down_revision: Union[str, None] = "b7d6261518f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    payment_status_enum = sa.Enum("CREATED", "PAID", name="paymentstatus")
    payment_status_enum.create(op.get_bind())

    op.add_column("payments", sa.Column("status", payment_status_enum, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("payments", "status")

    payment_status_enum = sa.Enum("CREATED", "PAID", name="paymentstatus")
    payment_status_enum.drop(op.get_bind())
    # ### end Alembic commands ###
