"""Add index to transaction_id field of payment

Revision ID: f6fc1e666d3c
Revises: 244d0fc9deb7
Create Date: 2025-04-15 13:50:24.101587

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6fc1e666d3c"
down_revision: Union[str, None] = "244d0fc9deb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("payments", "transaction_id", existing_type=sa.VARCHAR(length=100), nullable=False)
    op.create_index(op.f("ix_payments_transaction_id"), "payments", ["transaction_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_transaction_id"), table_name="payments")
    op.alter_column("payments", "transaction_id", existing_type=sa.VARCHAR(length=100), nullable=True)
    # ### end Alembic commands ###
